# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool: Default

steps:
- script: |
    /home/ldra-runner/ldra_toolsuite/contbbuildimport -build_cmd="make simple" -startindir=/home/myagent/_work/1/s/ -build -quit
    /home/ldra-runner/ldra_toolsuite/contestbed simple.btf 112a302120312panq
  displayName: 'Run a multi-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/ldra-runner/ldra_workarea/simple_tbwrkfls/simple_reports/'
    artifact: 'zip'
    publishLocation: 'pipeline'