# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- Run-Script

pool: Default

steps:
- script: |
    Run_LowLevelTests.sh
  displayName: 'Run a multi-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/ldra-runner/ldra_workarea/Cashregister_tbwrkfls/Cashregister_reports/'
    artifact: 'zip'
    publishLocation: 'pipeline'