# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- main

pool: Default

steps:
- script: |
    C:\LDRA_Toolsuite_C_CPP_10.1.0\contbuildimport -build_cmd="mingw32-make simple" - startin_dir=%CD% - build -quit
    C:\LDRA_Toolsuite_C_CPP_10.1.0\contestbed simple.btf /11234q
  displayName: 'Run a multi-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'C:\LDRA_Workarea_C_CPP_10.1.0\simple_tbwrkfls\simple_reports\'
    artifact: 'zip'
    publishLocation: 'pipeline'